### ISSUE TITLE
Possible release process for argo-ui

### ISSUE THREAD

**Issue by tetchel** [argoproj/argo-ui#94]
ArgoCD always pulls the master version of argo-ui ([link](https://github.com/argoproj/argo-cd/blob/master/ui/package.json#L30)), which is somewhat risky if breaking changes go into argo-ui. Consequently,  argo-ui `master` has to be highly stable.

Short of a proper release cycle, one easy way to stabilize this dependency is to create a "stable" branch which is manually rebased on the development branch. The development branch in GitHub terms would be the 'main' branch - the one PRs are targeted against by default. Currently, the `master` branch is both the development and stable branch. 

This manual rebase can be done periodically (eg weekly) or whenever the maintainer feels the development branch contains changes that are safe/stable enough. 

The advantage of this approach is a relatively cheap separation between stable and latest code on argo-ui, which allows low-cost "releases" that do not require updating any code in the projects that depend on argo-ui, since those projects are already targeting the stable branch. This reduces the testing overhead required for individual argo-ui PRs, since the stability of the development branch can be "lower".

The disadvantage of this approach is that it requires significant attention from a maintainer whose job it is to periodically rebase the stable branch on the development branch. The cost of reducing testing for individual PRs means that the testing is now batched into these periodic rebases, so the testing pre-rebase should be extensive.

The naming of the dev/stable branches is subjective. I would personally suggest leaving `master` as the dev/main branch and creating a new stable branch, eg `stable`, or `release`.

**Comment by alexec** [comment]
any reason to not just tag master?

**Comment by RichiCoder1** [comment]
Coming back to this, I'm a bit confused too. Tagging & releasing from master is the standard way to do this unless you plan on doing large chunks of unreleased work on master.

**Comment by rbreeze** [comment]
After discussing with @alexmt, we think using release branches is still a good idea so that we can push changes to master without fear of breaking Argo CD / Workflows UIs.

**Comment by alexec** [comment]
I'm not clear - what bugs have been introduced in Argo UI that means we need release branches? None I'm aware of. Why create a new process when the existing process works fine.

I'm really not clear what problem we are trying to solve.

**Comment by rbreeze** [comment]
I think the idea is that while thus far, no bugs have been introduced to warrant release branches, with an increase in scope there might be. Once we know changes introduced into Argo UI won't break anything, we'll feel more comfortable developing centralized UI components with more velocity. 

The problem I'd like to solve is making UI development for Argo as easy and consistent as possible, and I see that happening with a breadth of components that are actively developed (and documented) in this repo.

Also, since we are now releasing an NPM package starting [here](https://github.com/argoproj/argo-ui/pull/96) we can start using Argo UI as a 'normal' dependency in our projects rather than listing commits as dependencies. [This PR](https://github.com/argoproj/argo-ui/pull/102), a release method I stole from Rollouts, means we don't have to use release branches, but we can if we need to.
